### ISSUE TITLE
Large number of output files in ping experiment depletes inodes

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Experiments#1]
The ping experiment that ran on node 9 created 275769 files, rendering the /outdir largely unaccessible, and depleting inodes. 
With 915712 nodes total on that file system, that is not something we can continue doing.

**Comment by jonakarl** [comment]
This is due to the reposyncher not running or the repo being unavailable.

There is not much I can do about either of this from the perspective of the (ping) experiment container.

I would say that we need to monitor the /outdir (munin?) and if the space runs out we need to halt the pause or halt the experiment containers until the situation can be investigated (see whey the reposyncher is not running or why the repo is not available)

**Comment by relet** [comment]
How about appending to an existing file, if it exists? That's what we do on our routers.
That would also prevent loss of measurement data in the case that the repository is not reachable.

**Comment by jonakarl** [comment]
After an offline disucssion this will be solved at the synchronization step. I will therefore close this issue.
